### PR TITLE
fix(build): enable position independent  code

### LINKED ISSUE #14: Linking failing when building in Ubuntu 22.04
When building the runtime using clang in linux (Ubuntu 22.04) the compilation fails when linking with

```
/usr/bin/ld: Lib/libopenvdb.a(Grid.cc.o): relocation R_X86_64_PC32 against symbol `_ZTVN7openvdb5v10_18KeyErrorE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/picogk.dir/build.make:156: lib/picogk.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/picogk.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I can fix this by adding the following to CMakeLists.txt (I put it at line 90)

```
#enable position independent code
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```

Though I'm not sure if this will break the build for other os's

### PR DESCRIPTION
**Pull request by gnikit**
I attempted to match the existing cmake style.
CMake doc reference: https://cmake.org/cmake/help/latest/module/CheckPIESupported.html#checkpiesupported

Fixes #14

### CODE REVIEW

**Comment by gnikit** [comment]
@LinKayser I saw this ended up being reverted. Did the change have side effects in your internal build/packaging process?

**Comment by LinKayser** [comment]
Apologies — I accidentally merged to Master and reverted. In my first test CMake choked on it on Mac, so I need to investigate further. [We were busy with this last week](https://leap71.com/2024/06/18/leap-71-hot-fires-3d-printed-liquid-fuel-rocket-engine-designed-through-noyron-computational-model/), so I didn't have time to investigate yet.

**Comment by gnikit** [comment]
Congrats on engine and Noyron, they are both insanely cool accomplishments.

With regards to cmake. This definitely should not happen. I'll check on my Mac as well. I know that the last line works on  all major platforms, so it's probably the things above.

**Comment by gnikit** [comment]
```
check_pie_supported(OUTPUT_VARIABLE output LANGUAGES C CXX)
```

I can confirm, behaviour across compilers/platforms is inconsistent. I think this is unexpected behaviour, so I'll look into it a bit more and if nothing comes up, I'll raise it over at cmake.

The solution is to only add 

```
set(CMAKE_POSITION_INDEPENDENT_CODE TRUE)
```

Moving forward I think the safest solution is to have a CI pipeline that tests the supported compilers and OSs. I have made a start over at my fork and I'll open a PR once done.

**Pull request merged**
