### PR TITLE
Update Mac.sh - Add doxygen

### PR DESCRIPTION
**Pull request by Niels-IO**
Cmake Configure step errored as doxygen was not installed on my system (M1 Mac). Add it as a necessary package

### CODE REVIEW

**Comment by LinKayser** [comment]
Hmmm, we don't use doxygen and I don't want to require it. Can you post what error you are getting? I am not getting any on all of our systems, and none have doxygen installed.

**Comment by Niels-IO** [comment]
Hi Lin,

This is the error output I get in the GUI from CMake (after uninstalling doxygen to reproduce the error)

> CMake Build Type: Release
> Configuring for OpenVDB Version 10.1.0
> Configuring for OpenVDB ABI Version 10
> ----------------------------------------------------
> ------------- Configuring OpenVDBCore --------------
> ----------------------------------------------------
> Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
> Found TBB: /opt/homebrew/include (found suitable version "2021.11", minimum required is "2020.2") found components: tbb 
> ----------------------------------------------------
> ----------- Configuring OpenVDBBinaries ------------
> ----------------------------------------------------
> Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
> Found TBB: /opt/homebrew/include (found suitable version "2021.11", minimum required is "2020.2") found components: tbbmalloc 
> Populating glfw
> -- Configuring done (0.0s)
> 
> -- Generating done (0.0s)
> 
> -- Build files have been written to: /Users/niels/Documents/code/picogk_test/PicoGKRuntime/GLFW/glfw-subbuild
> 
> [ 11%] Performing update step for 'glfw-populate'
> 
> [ 22%] No patch step for 'glfw-populate'
> 
> [ 33%] No configure step for 'glfw-populate'
> 
> [ 44%] No build step for 'glfw-populate'
> 
> [ 55%] No install step for 'glfw-populate'
> 
> [ 66%] No test step for 'glfw-populate'
> 
> [ 77%] Completed 'glfw-populate'
> 
> [100%] Built target glfw-populate
> 
> CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.28/Modules/FindDoxygen.cmake:494 (message):
>   Doxygen executable failed unexpected while determining version (exit
>   status: no such file or directory).  Disabling Doxygen.
> Call Stack (most recent call first):
>   /Applications/CMake.app/Contents/share/cmake-3.28/Modules/FindDoxygen.cmake:659 (_Doxygen_find_doxygen)
>   GLFW/glfw-src/CMakeLists.txt:66 (find_package)
> 
> 
> Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
> Using Cocoa for window creation
> Configuring done (0.5s)

**Comment by LinKayser** [comment]
Hi Niels — this is just a warning, so I think we can just ignore it. If Doxygen is insalled, then you can use it to generate the GLFW docs, which is not important for us.

**Comment by Niels-IO** [comment]
Hi Lin, 
Perfect, thanks for looking into it!

**Pull request closed without merging**
